format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust\
$golang\
$ruby\
$cmd_duration\
$character"""

[directory]
style = "bold blue"
read_only = " "
truncation_length = 3
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[â®](bold yellow)"

[git_branch]
symbol = ""
format = "on [$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"
conflicted = "="
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "?${count}"
stashed = "$"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "âœ˜${count}"

[nodejs]
symbol = "â¬¢"
format = " [$symbol $version]($style)"
style = "green"

[python]
symbol = "ğŸ"
format = " [$symbol $pyversion]($style)"
style = "yellow"

[rust]
symbol = "ğŸ¦€"
format = " [$symbol $version]($style)"
style = "red"

[golang]
symbol = "ğŸ¹"
format = " [$symbol $version]($style)"
style = "cyan"

[ruby]
symbol = "ğŸ’"
format = " [$symbol $version]($style)"
style = "red"

[cmd_duration]
min_time = 5_000
format = " took [$duration](yellow)"
show_milliseconds = false
